### ISSUE TITLE
Clarifications re new schema for specs

### ISSUE THREAD

**Issue by rufuspollock** [datahq/specstore#6]
* [x] How do you provide a table schema for a sheet in an excel file (`resource_info` is on the resource not in the processing step ...)
* [x] resource-mapping vs resource_info seems inconsistent - should we not have always \_ vs - (or vice versa)  
* [ ] ~Why do we have resource_info as well as info in the data package?~ - [@zelima] no more relevant, we use the whole descriptor instead of resource info
  * @akariv Reason for that information is that in order to plan the different pipelines, we need to know which resources are in the datapackage - but we don’t want to load the datapackage for that (as it’s an expensive network operation). We want all the information necessary for creating the plan readily available in the assembly spec.
  * @rufuspollock should we just post the datapackage.json along with source spec directly to the specstore? (we can always cache original in rawstore)?
  * @akariv Not sure, datapackages can get quite big. This is the reason I’m selectively choosing only a handful of properties to be added to the sourcespec.
* [ ] Would be super useful to have an illustration of how this should look for e.g. an excel file and a csv where we want to delete the first 5 rows ...

**Comment by anuveyatsu** [comment]
Q: How do you provide a table schema for a sheet in an excel file (resource_info is on the resource not in the processing step ...)

A: We provide a schema for the first sheet along with Excel resource. For the rest of sheets, we provide schemas in source spec:

```yaml=
processing:
 - # Processing steps that need to be done on sources to get proper data streams
   input: <source-resource-name - e.g. `my-excel-resource`>
   output: <destination-resource-name - e.g. `my-excel-resource-sheet-1`>
   tabulator: # Currently we're only supporting tabulator transformations
     # These are sample options for tabulator, see its docs for all available options
     headers: 2 
     sheet: 1
   schema: # Overwrite schema for resource
     fields:
       - name: bla
         type: string
       # table schema
```

**Comment by rufuspollock** [comment]
hey @akariv can you update here esp regarding examples 😄

**Comment by zelima** [comment]
We now include datapackage.json into flow-spec. 

Here is an example flow.yaml for the dataset that deletes first 2 lines and adds headers. - https://github.com/datasets/finance-vix/blob/master/.datahub/flow.yaml

Here is how you can define: 
* `skip_rows: 2` will delete first 2 rows
* `headers` will set header
```
processing:
  -
    input: vix-daily
    tabulator:
      skip_rows: 2
      headers:
        - Date
        - VIXOpen
        - VIXHigh
        - VIXLow
        - VIXClose
    output: vix-daily
```
